<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>javascript异常捕获</title>
</head>
<body>
    <!--
    try 语句测试代码块的错误。
    catch 语句处理错误。
    throw 语句创建自定义错误
    -->
    <!--JavaScript 测试和捕捉-->
    <!--
    try 语句允许我们定义在执行时进行错误测试的代码块。
    catch 语句允许我们定义当 try 代码块发生错误时，所执行的代码块。
    JavaScript 语句 try 和 catch 是成对出现的。
    -->

    <!--语法-->
    <!--
    try
      {
      //在这里运行代码
      }
    catch(err)
      {
      //在这里处理错误
      }
    -->

    <!--<script>-->
        <!--var text;-->
        <!--function func() {-->
            <!--try{adddlesrt("Welcome chain dianxin")}-->
            <!--catch (err) {-->
                <!--alert(text);-->
            <!--}-->
        <!--}-->
    <!--</script>-->
    <!--<input type="button" value="点击查看" onclick="func()">-->




















</body>
</html>